const Employee = require('../models/Employee'); const Department = require('../models/Department'); const Designation = require('../models/Designation'); const EmployeeHistory = require('../models/EmployeeHistory'); const { logAudit } = require('../services/auditService');
const list = (Model, populate = '') => async (req, res) => { const { page = 1, limit = 20, search = '', sort = '-createdAt' } = req.query; const filter = search ? { $or: ['name','employeeCode','assetTag','documentNumber'].map(key => ({ [key]: { $regex: search, $options: 'i' } })) } : {}; const [items,total] = await Promise.all([Model.find(filter).populate(populate).sort(sort).skip((page-1)*limit).limit(Number(limit)), Model.countDocuments(filter)]); res.json({ items, pagination: { page: Number(page), limit: Number(limit), total, totalPages: Math.ceil(total/limit) } }); };
exports.listEmployees = list(Employee, 'userId departmentId designationId managerId');
exports.getMyEmployee = async (req,res) => { const employee = await Employee.findOne({ userId: req.user._id || req.user.userId }).populate('departmentId designationId managerId'); if (!employee) return res.status(404).json({ message:'Employee profile not found' }); res.json(employee); };
exports.getEmployee = async (req,res) => { const employee = await Employee.findById(req.params.id).populate('userId departmentId designationId managerId'); if (!employee) return res.status(404).json({ message:'Employee not found' }); res.json(employee); };
exports.createEmployee = async (req,res) => { const employee = await Employee.create(req.body); await logAudit({req,action:'CREATE',resourceEntity:'Employee',resourceId:employee._id,changes:{new:req.body}}); res.status(201).json(employee); };
exports.updateEmployee = async (req,res) => { const old = await Employee.findById(req.params.id).lean(); const employee = await Employee.findByIdAndUpdate(req.params.id, req.body, {new:true,runValidators:true}); if (!employee) return res.status(404).json({message:'Employee not found'}); await EmployeeHistory.create({employeeId:employee._id,event:'profile_updated',before:old,after:req.body,changedBy:req.user._id}); await logAudit({req,action:'UPDATE',resourceEntity:'Employee',resourceId:employee._id,changes:{old,new:req.body}}); res.json(employee); };
exports.departments = { list:list(Department), create: async(req,res)=>res.status(201).json(await Department.create(req.body)), update:async(req,res)=>res.json(await Department.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true})) };
exports.designations = { list:list(Designation,'departmentId'), create:async(req,res)=>res.status(201).json(await Designation.create(req.body)), update:async(req,res)=>res.json(await Designation.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true})) };
